//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildRoadApp_Api.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANIMAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANIMAL()
        {
            this.REPORTs = new HashSet<REPORT>();
        }
    
        public int id { get; set; }
        public string common_name { get; set; }
        public string scientific_name { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public byte[] is_endangered { get; set; }
        public string clasification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORT> REPORTs { get; set; }
    }
}
