//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildRoadApp_Api.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cluster_Info
    {
        public string accident_number { get; set; }
        public Nullable<int> cluster_no { get; set; }
    
        public virtual HISTORY_REPORT HISTORY_REPORT { get; set; }
    }
}
