//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildRoadApp_Api.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEO_FENCE
    {
        public int fence_id { get; set; }
        public string accident_no { get; set; }
        public string fence_name { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public double risk_grade { get; set; }
    }
}
