//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildRoadApp_Api.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEOFENCE
    {
        public int id_geofence { get; set; }
        public string name { get; set; }
        public string north_pos { get; set; }
        public string east_pos { get; set; }
        public string west_pos { get; set; }
        public string south_pos { get; set; }
    }
}
