//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildRoadApp_Api.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY_REPORT
    {
        public string accident_number { get; set; }
        public string accident_date { get; set; }
        public string accident_time { get; set; }
        public string day_week_desc { get; set; }
        public string light_condition_desc { get; set; }
        public int severity { get; set; }
        public int speed_zone { get; set; }
        public string lg_area_name { get; set; }
        public string region_name { get; set; }
        public string deg_urban_name { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public int postcode { get; set; }
        public string nearest_national_park_name { get; set; }
    
        public virtual Cluster_Info Cluster_Info { get; set; }
    }
}
