//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildRoadApp_Api.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENT
    {
        public int incident_id { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string suburb { get; set; }
        public Nullable<short> people_hurt { get; set; }
        public string animal { get; set; }
        public string incident_date { get; set; }
        public string comments { get; set; }
        public int incident_type { get; set; }
        public string userId_report { get; set; }
    
        public virtual INCIDENT_TYPE INCIDENT_TYPE1 { get; set; }
    }
}
