//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildRoadApp_Api.DataManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WildRoadDBEntities : DbContext
    {
        public WildRoadDBEntities()
            : base("name=WildRoadDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALERT> ALERTs { get; set; }
        public virtual DbSet<ANIMAL> ANIMALs { get; set; }
        public virtual DbSet<APPUSER> APPUSERs { get; set; }
        public virtual DbSet<BuildVersion> BuildVersions { get; set; }
        public virtual DbSet<Cluster_Info> Cluster_Info { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<GEOFENCE> GEOFENCEs { get; set; }
        public virtual DbSet<HISTORY_REPORT> HISTORY_REPORT { get; set; }
        public virtual DbSet<NATIONAL_PARK> NATIONAL_PARK { get; set; }
        public virtual DbSet<REPORT> REPORTs { get; set; }
        public virtual DbSet<TYPE_REPORT> TYPE_REPORT { get; set; }
        public virtual DbSet<ACCIDENT_TREND> ACCIDENT_TREND { get; set; }
        public virtual DbSet<GEO_FENCE> GEO_FENCE { get; set; }
        public virtual DbSet<INCIDENT> INCIDENTs { get; set; }
        public virtual DbSet<INCIDENT_TYPE> INCIDENT_TYPE { get; set; }
    }
}
