//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildRoadApp_Api.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class NATIONAL_PARK
    {
        public int np_id { get; set; }
        public string np_name { get; set; }
        public string np_description { get; set; }
        public string np_longitude { get; set; }
        public string np_latitude { get; set; }
        public Nullable<int> np_frequency { get; set; }
        public string np_picture_link { get; set; }
    }
}
