//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildRoadApp_Api.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT
    {
        public int id_report { get; set; }
        public string location { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string departure_location { get; set; }
        public string destination_location { get; set; }
        public int type_report_report_id { get; set; }
        public int ANIMAL_id { get; set; }
        public int user_id_user { get; set; }
    
        public virtual ANIMAL ANIMAL { get; set; }
        public virtual APPUSER APPUSER { get; set; }
        public virtual TYPE_REPORT TYPE_REPORT { get; set; }
    }
}
